export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  calories: number;
  category: string;
  image: any;
  isPopular?: boolean;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  isVeg?: boolean;
  badge?: string;
}

export interface Category {
  id: string;
  label: string;
  icon: string;
}

export const categories: Category[] = [
  { id: "all", label: "All", icon: "grid" },
  { id: "burgers", label: "Burgers", icon: "circle" },
  { id: "pizza", label: "Pizza", icon: "disc" },
  { id: "momos", label: "Momos", icon: "package" },
  { id: "wraps", label: "Wraps", icon: "rotate-cw" },
  { id: "chicken", label: "Chicken", icon: "star" },
  { id: "coffee", label: "Coffee", icon: "coffee" },
  { id: "mojitos", label: "Mojitos", icon: "droplet" },
  { id: "desserts", label: "Desserts", icon: "heart" },
];

export const menuItems: MenuItem[] = [
  {
    id: "b1",
    name: "Zinger Burger",
    description: "Crispy golden chicken fillet, fresh lettuce, signature sauce, toasted sesame bun",
    price: 199,
    calories: 480,
    category: "burgers",
    image: require("@/assets/images/burger.png"),
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    badge: "Fan Favourite",
  },
  {
    id: "b2",
    name: "Temptation Special Burger",
    description: "Double patty, cheese, caramelized onion, jalapeños, house secret sauce",
    price: 269,
    calories: 620,
    category: "burgers",
    image: require("@/assets/images/burger.png"),
    isFeatured: true,
    badge: "Chef's Pick",
  },
  {
    id: "b3",
    name: "Classic Chicken Burger",
    description: "Juicy grilled chicken, fresh veggies, tangy mayo on brioche bun",
    price: 169,
    calories: 420,
    category: "burgers",
    image: require("@/assets/images/burger.png"),
  },
  {
    id: "b4",
    name: "Double Smash Burger",
    description: "Two smashed beef patties, American cheese, pickles, special sauce",
    price: 319,
    calories: 720,
    category: "burgers",
    image: require("@/assets/images/burger.png"),
    badge: "New",
  },
  {
    id: "p1",
    name: "Cheese Burst Pizza",
    description: "Loaded crust stuffed with cheese, fresh mozzarella, tomato base",
    price: 349,
    calories: 780,
    category: "pizza",
    image: require("@/assets/images/hero_banner.png"),
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "p2",
    name: "Chicken BBQ Pizza",
    description: "Smoky BBQ chicken, bell peppers, red onion, mozzarella",
    price: 319,
    calories: 710,
    category: "pizza",
    image: require("@/assets/images/hero_banner.png"),
    isPopular: true,
  },
  {
    id: "p3",
    name: "Margherita",
    description: "Fresh basil, premium mozzarella, San Marzano tomato sauce",
    price: 249,
    calories: 580,
    category: "pizza",
    image: require("@/assets/images/hero_banner.png"),
    isVeg: true,
  },
  {
    id: "m1",
    name: "Steamed Momos",
    description: "Delicate dumplings filled with spiced chicken, served with chili sauce",
    price: 149,
    calories: 280,
    category: "momos",
    image: require("@/assets/images/popcorn.png"),
    isPopular: true,
  },
  {
    id: "m2",
    name: "Fried Momos",
    description: "Crispy pan-fried dumplings with chicken filling, spicy dip",
    price: 169,
    calories: 340,
    category: "momos",
    image: require("@/assets/images/popcorn.png"),
    isFeatured: true,
  },
  {
    id: "m3",
    name: "Tandoori Momos",
    description: "Smoky tandoor-fired momos with tikka spices, mint chutney",
    price: 199,
    calories: 360,
    category: "momos",
    image: require("@/assets/images/popcorn.png"),
    badge: "Spicy",
  },
  {
    id: "w1",
    name: "Chicken Wrap",
    description: "Grilled chicken strips, crisp veggies, cheese sauce in soft tortilla",
    price: 179,
    calories: 390,
    category: "wraps",
    image: require("@/assets/images/hero_banner.png"),
    isPopular: true,
    isBestSeller: true,
  },
  {
    id: "w2",
    name: "Zinger Wrap",
    description: "Crispy zinger fillet, coleslaw, special sauce wrapped tight",
    price: 199,
    calories: 430,
    category: "wraps",
    image: require("@/assets/images/hero_banner.png"),
  },
  {
    id: "c1",
    name: "Chicken Popcorn",
    description: "Bite-sized crispy chicken bites, seasoned with our secret spice blend",
    price: 179,
    calories: 380,
    category: "chicken",
    image: require("@/assets/images/popcorn.png"),
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    badge: "Fan Favourite",
  },
  {
    id: "c2",
    name: "Chicken Wings",
    description: "Slow-cooked, sauced wings — choose from BBQ, Buffalo, or Honey Garlic",
    price: 249,
    calories: 520,
    category: "chicken",
    image: require("@/assets/images/popcorn.png"),
    isPopular: true,
    badge: "Must Try",
  },
  {
    id: "c3",
    name: "Chicken Strips",
    description: "Premium breast strips, panko crusted, served with dipping sauce",
    price: 219,
    calories: 460,
    category: "chicken",
    image: require("@/assets/images/popcorn.png"),
  },
  {
    id: "cf1",
    name: "Cappuccino",
    description: "Rich espresso, velvety steamed milk foam, artisan pour",
    price: 129,
    calories: 120,
    category: "coffee",
    image: require("@/assets/images/hero_banner.png"),
    isVeg: true,
  },
  {
    id: "cf2",
    name: "Cold Coffee",
    description: "Double-shot cold brew blended with premium cream and ice",
    price: 149,
    calories: 180,
    category: "coffee",
    image: require("@/assets/images/hero_banner.png"),
    isPopular: true,
    isVeg: true,
  },
  {
    id: "cf3",
    name: "Caramel Latte",
    description: "Smooth espresso, steamed milk, house caramel drizzle",
    price: 159,
    calories: 210,
    category: "coffee",
    image: require("@/assets/images/hero_banner.png"),
    isVeg: true,
  },
  {
    id: "mj1",
    name: "Temptation Special Mojito",
    description: "Our signature blend — exotic fruits, fresh mint, premium soda, zesty lime",
    price: 179,
    calories: 160,
    category: "mojitos",
    image: require("@/assets/images/mojito.png"),
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    badge: "Signature",
    isVeg: true,
  },
  {
    id: "mj2",
    name: "Blue Lagoon Mojito",
    description: "Electric blue curacao, lime, mint, sparkling soda — visually stunning",
    price: 169,
    calories: 150,
    category: "mojitos",
    image: require("@/assets/images/mojito.png"),
    isVeg: true,
    badge: "Popular",
  },
  {
    id: "mj3",
    name: "Virgin Mojito",
    description: "Classic fresh lime, mint leaves, sugar syrup, soda water",
    price: 149,
    calories: 130,
    category: "mojitos",
    image: require("@/assets/images/mojito.png"),
    isVeg: true,
  },
  {
    id: "mj4",
    name: "Strawberry Mojito",
    description: "Fresh strawberries, basil, lime, mint — summer in a glass",
    price: 179,
    calories: 165,
    category: "mojitos",
    image: require("@/assets/images/mojito.png"),
    isVeg: true,
  },
  {
    id: "d1",
    name: "Chocolate Brownie",
    description: "Warm fudge brownie, vanilla ice cream, chocolate sauce drizzle",
    price: 129,
    calories: 480,
    category: "desserts",
    image: require("@/assets/images/hero_banner.png"),
    isVeg: true,
    isPopular: true,
  },
  {
    id: "d2",
    name: "Ice Cream Sundae",
    description: "Three scoops, hot fudge, whipped cream, cherry on top",
    price: 99,
    calories: 380,
    category: "desserts",
    image: require("@/assets/images/hero_banner.png"),
    isVeg: true,
  },
];

export const offers = [
  {
    id: "o1",
    title: "Happy Hours",
    subtitle: "20% OFF on all Mojitos",
    time: "4 PM – 7 PM",
    code: "HAPPY20",
    color: "#1A3A1A",
    accent: "#4CAF50",
  },
  {
    id: "o2",
    title: "Burger + Mojito",
    subtitle: "Combo at just ₹299",
    time: "All Day",
    code: "COMBO299",
    color: "#1A1A3A",
    accent: "#C8973A",
  },
  {
    id: "o3",
    title: "Weekend Feast",
    subtitle: "Buy 2 Get 1 FREE on Wings",
    time: "Sat & Sun Only",
    code: "WINGS3",
    color: "#3A1A1A",
    accent: "#E53935",
  },
];

export const reviews = [
  {
    id: "r1",
    name: "Rahul M.",
    rating: 5,
    text: "Zinger Burger is absolutely fantastic! Best in Kalaburagi hands down. The ambience is great too.",
    time: "2 days ago",
  },
  {
    id: "r2",
    name: "Priya S.",
    rating: 5,
    text: "The Temptation Special Mojito is a must-try! So refreshing and unique. Will definitely come back.",
    time: "1 week ago",
  },
  {
    id: "r3",
    name: "Arjun K.",
    rating: 4,
    text: "Chicken Popcorn is crispy and perfectly seasoned. Great place to hang out with friends!",
    time: "2 weeks ago",
  },
  {
    id: "r4",
    name: "Sneha R.",
    rating: 5,
    text: "Love the dark cozy ambience. Food quality is top notch and pricing is very reasonable.",
    time: "3 weeks ago",
  },
];
