uploads = []
outputs = []

[[generated]]
id = "OIySdNzy-CcAc4PNPsT0y"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FrRK_ulEW8d6iakl93P2I"
uri = "file://artifacts/mobile/assets/images/hero_banner.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EEIxNgIR8Mxyw9uxLAT69"
uri = "file://artifacts/mobile/assets/images/burger.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ntCetyr_hTN9_YbyOHLPe"
uri = "file://artifacts/mobile/assets/images/mojito.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WD1eGiEQvoioOJhCjlF3R"
uri = "file://artifacts/mobile/assets/images/popcorn.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ADjanvAXafZ1qBIeT_KO5"
uri = "file://artifacts/mobile/assets/images/splash_bg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UBfW15fXz6rNOy0Fag4MP"
uri = "file://artifacts/mobile/assets/images/pizza.png"
type = "image"
title = "generated_image"

[[generated]]
id = "N2bOgR12A3Y3CPSTphXuo"
uri = "file://artifacts/mobile/assets/images/coffee.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Shf606Wb40YGGm5DhipkP"
uri = "file://artifacts/mobile/assets/images/wings.png"
type = "image"
title = "generated_image"

[[generated]]
id = "AOyDIw1hQh5Vv0IzSl8hl"
uri = "file://artifacts/mobile/assets/images/wrap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UxCp4C0rMMQlcgETWL9fl"
uri = "file://artifacts/mobile/assets/images/ambience.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SKhhIwwVpyDCNSUNZJCcF"
uri = "file://artifacts/mobile/assets/images/event_birthday.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wID6bXGRaud6tNfbkyIrG"
uri = "file://artifacts/mobile/assets/images/momos.png"
type = "image"
title = "generated_image"
