uploads = []
outputs = []

[[generated]]
id = "OIySdNzy-CcAc4PNPsT0y"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FrRK_ulEW8d6iakl93P2I"
uri = "file://artifacts/mobile/assets/images/hero_banner.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EEIxNgIR8Mxyw9uxLAT69"
uri = "file://artifacts/mobile/assets/images/burger.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ntCetyr_hTN9_YbyOHLPe"
uri = "file://artifacts/mobile/assets/images/mojito.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WD1eGiEQvoioOJhCjlF3R"
uri = "file://artifacts/mobile/assets/images/popcorn.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ADjanvAXafZ1qBIeT_KO5"
uri = "file://artifacts/mobile/assets/images/splash_bg.png"
type = "image"
title = "generated_image"
